# Generated by Django 6.0.3 on 2026-03-08 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("scraper", "0011_update_asset_view_user_and_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="watchlist",
        ),
        migrations.CreateModel(
            name="UserAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_watchlist", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "price_target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assets",
                        to="scraper.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "asset")},
            },
        ),
    ]
