ASSET_DETAIL_FAVICON_SIZE = 256
ASSET_DETAIL_RECENT_PRICES_DAYS = 30
ASSET_DETAIL_REDDIT_POSTS = 20
ASSET_DETAIL_HN_POSTS = 20
ASSET_DETAIL_NEWS_ARTICLES = 10
RSI_PERIOD = 21
DEFAULT_CHART_RANGE = "1W"

HOME_COUNTS_CACHE_TTL = 600  # 10 minutes
CHART_DATA_CACHE_TTL = 1800  # 30 minutes
PRICES_CACHE_TTL = 1800  # 30 minutes
COMMUNITY_CACHE_TTL = 900  # 15 minutes
PEERS_CACHE_TTL = 259200  # 72 hours

SEARCH_MAX_RESULTS = 6
SEARCH_MIN_QUERY_LENGTH = 1
SPARKLINE_DATA_POINTS = 30
