ASSET_DETAIL_FAVICON_SIZE = 256
ASSET_DETAIL_RECENT_PRICES_DAYS = 30
PRICES_PAGE_DAYS = 30
ASSET_DETAIL_REDDIT_POSTS = 20
ASSET_DETAIL_HN_POSTS = 20
ASSET_DETAIL_NEWS_ARTICLES = 10
RSI_PERIOD = 14
DEFAULT_CHART_RANGE = "1W"

HOME_COUNTS_CACHE_TTL = 600  # 10 minutes
PRICES_CACHE_TTL = 3600  # 1 hour — matches hourly price sync interval
PEERS_CACHE_TTL = 1800  # 30 minutes

SEARCH_MAX_RESULTS = 6
SEARCH_MIN_QUERY_LENGTH = 1
SPARKLINE_DATA_POINTS = 30

TRENDING_BANNER_COUNT = 20
TRENDING_CACHE_TTL = 300  # 5 minutes
TRENDING_REFRESH_INTERVAL = 300  # seconds — HTMX polling interval
TRENDING_PERIOD_H = 168  # 7 days
VIEW_COOLDOWN_H = 1  # hours before same visitor/user can count as a new view

REPORT_SECTION_POLL_INTERVAL_S = (
    5  # seconds — HTMX polling interval for report card sections
)
