# Generated by Django 6.0.3 on 2026-03-07 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=300)),
                ("summary", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                (
                    "url",
                    models.URLField(blank=True, max_length=500, null=True, unique=True),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("earnings", "Earnings"),
                            ("macro", "Macroeconomic"),
                            ("regulatory", "Regulatory"),
                            ("geopolitical", "Geopolitical"),
                            ("sector", "Sector"),
                            ("company", "Company"),
                            ("market", "Market"),
                        ],
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "news",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsAssetImpact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("stagnant", "Stagnant"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "magnitude",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_impacts",
                        to="scraper.asset",
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impacts",
                        to="scraper.news",
                    ),
                ),
            ],
            options={
                "ordering": ["-news__published_at"],
                "unique_together": {("news", "asset")},
            },
        ),
        migrations.AddField(
            model_name="news",
            name="assets",
            field=models.ManyToManyField(
                related_name="news",
                through="scraper.NewsAssetImpact",
                to="scraper.asset",
            ),
        ),
    ]
