# Generated by Django 6.0.3 on 2026-03-07 23:20

import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_redditpost'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='redditpost',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=2048, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
