# Generated by Django 6.0.3 on 2026-03-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0004_redditpost_embedding_alter_pricehistory_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
