# Generated by Django 6.0.3 on 2026-03-07 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0005_add_website_to_asset"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedditComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reddit_id", models.CharField(max_length=20, unique=True)),
                ("author", models.CharField(max_length=50)),
                ("body", models.TextField()),
                ("score", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="scraper.redditpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
            },
        ),
    ]
