# Generated by Django 6.0.3 on 2026-03-08 04:10

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0006_redditcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundamental",
            name="debt_to_equity",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="fundamental",
            name="free_cash_flow",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=24, null=True
            ),
        ),
        migrations.AddField(
            model_name="fundamental",
            name="price_to_book",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="fundamental",
            name="return_on_equity",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=8, null=True
            ),
        ),
        migrations.CreateModel(
            name="HNPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hn_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("author", models.CharField(max_length=50)),
                ("score", models.IntegerField()),
                ("num_comments", models.IntegerField()),
                ("posted_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=2048, null=True
                    ),
                ),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True, related_name="hn_posts", to="scraper.asset"
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_at"],
            },
        ),
        migrations.CreateModel(
            name="HNComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hn_id", models.IntegerField(unique=True)),
                ("author", models.CharField(max_length=50)),
                ("body", models.TextField()),
                ("posted_at", models.DateTimeField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="scraper.hnpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_at"],
            },
        ),
    ]
