# Generated by Django 6.0.3 on 2026-03-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_widen_percentage_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
