# Generated by Django 6.0.3 on 2026-03-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0016_add_report_card_fields_to_asset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="url",
            field=models.URLField(blank=True, max_length=2048, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="thumbnail",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="url",
            field=models.URLField(max_length=2048, unique=True),
        ),
    ]
