# Generated by Django 6.0.3 on 2026-03-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0017_increase_url_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-posted_at'], 'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-posted_at']},
        ),
        migrations.AlterModelOptions(
            name='newsassetimpact',
            options={'ordering': ['-news__posted_at']},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='published_at',
            new_name='posted_at',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='published_at',
            new_name='posted_at',
        ),
    ]
