# Generated by Django 6.0.3 on 2026-03-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0018_alter_news_options_alter_newsarticle_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_class",
            field=models.CharField(
                choices=[
                    ("crypto", "Crypto"),
                    ("equity", "Equity"),
                    ("commodity", "Commodity"),
                    ("currency", "Currency"),
                ],
                max_length=10,
            ),
        ),
    ]
