# Generated by Django 6.0.3 on 2026-03-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0019_alter_asset_asset_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='report_card_score',
            new_name='market_score',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='report_card_updated_at',
            new_name='market_score_updated_at',
        ),
    ]
